# Generated by Django 4.0 on 2021-12-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='customtrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('departure', models.DateField()),
                ('end', models.DateField()),
                ('fullname', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('arrivalairport', models.CharField(blank=True, max_length=100, null=True)),
                ('departureairport', models.CharField(blank=True, max_length=100, null=True)),
                ('whom', models.CharField(blank=True, max_length=100, null=True)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('specialrequest', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
