# Generated by Django 4.0 on 2021-12-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customtrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtrip',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='customtrip',
            name='end',
        ),
        migrations.AddField(
            model_name='customtrip',
            name='tour_dates',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
