# Generated by Django 4.0 on 2021-12-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staycation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staycation_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(choices=[('Hotel & Resorts', 'Hotel & Resorts'), ('Home & Villas', 'Home & Villas')], default='Hotel & Resorts', max_length=100)),
                ('recommended', models.BooleanField(default=False)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=1000)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='staycation')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='staycation')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='staycation')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='staycation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='staycation')),
                ('host_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
