# Generated by Django 4.0 on 2021-12-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staycation',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='staycation',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='staycation',
            name='image3',
        ),
        migrations.AddField(
            model_name='staycation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
