# Generated by Django 4.0 on 2021-12-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staycation', '0003_alter_staycation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaycationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('cancellationpolicy', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('inclusion', models.TextField(blank=True, null=True)),
                ('roompolicies', models.TextField(blank=True, null=True)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='staycation')),
                ('host_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('staycation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staycation.staycation')),
            ],
        ),
    ]
