# Generated by Django 4.0 on 2021-12-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0004_staycationroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staycationroom',
            name='cancellationpolicy',
        ),
        migrations.AddField(
            model_name='staycationroom',
            name='roomfacilites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
