# Generated by Django 4.0 on 2021-12-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0007_alter_roomprice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='staycationroom',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staycation',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
