# Generated by Django 4.0 on 2021-12-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0008_staycationroom_slug_alter_staycation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='room_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomprice', to='staycation.staycationroom'),
        ),
    ]
