# Generated by Django 4.0 on 2021-12-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0009_alter_roomprice_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='room_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staycation.staycationroom'),
        ),
    ]
