# Generated by Django 4.0 on 2021-12-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0011_staycationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staycation',
            name='category',
            field=models.CharField(choices=[('Hotel-Resorts', 'Hotel & Resorts'), ('Home-Villas', 'Home & Villas')], default='Hotel & Resorts', max_length=100),
        ),
    ]
