# Generated by Django 4.0 on 2021-12-31 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0013_remove_staycationrequest_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staycationimg')),
                ('staycation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staycation.staycation')),
            ],
        ),
    ]
