# Generated by Django 4.0 on 2022-03-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staycation', '0014_featureimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='staycation',
            name='video_id',
            field=models.CharField(default='None', max_length=5000),
        ),
    ]
