# Generated by Django 4.0 on 2021-12-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('tour_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('recommended', models.BooleanField(default=False)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('price_includes', models.TextField(blank=True, null=True)),
                ('price_not_includes', models.TextField(blank=True, null=True)),
                ('departure', models.CharField(blank=True, max_length=100)),
                ('end', models.CharField(blank=True, max_length=100)),
                ('countries', models.CharField(blank=True, max_length=1000)),
                ('cities', models.CharField(blank=True, max_length=1000)),
                ('flight', models.CharField(choices=[('Excluded', 'Excluded'), ('Included', 'Included')], default='Excluded', max_length=100)),
                ('guide', models.CharField(choices=[('Excluded', 'Excluded'), ('Included', 'Included')], default='Excluded', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourimg')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.category', to_field='slug')),
                ('host_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
