# Generated by Django 4.0 on 2021-12-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_featureimages_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='tournew',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
