# Generated by Django 4.0 on 2021-12-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tour', '0004_remove_days_tournew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.category', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='host_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
