# Generated by Django 4.0 on 2021-12-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tour', '0005_alter_tour_category_alter_tour_countries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.IntegerField(default=0)),
                ('daparture_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('accomodation', models.CharField(max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_number', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.TextField(blank=True, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('host_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
    ]
