# Generated by Django 4.0 on 2021-12-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_tourrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='tourdates',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
