# Generated by Django 4.0 on 2021-12-31 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_tourrequest_tourdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourrequest',
            old_name='tourdates',
            new_name='tour_dates',
        ),
        migrations.RemoveField(
            model_name='tourrequest',
            name='daparture_date',
        ),
        migrations.RemoveField(
            model_name='tourrequest',
            name='end_date',
        ),
    ]
