# Generated by Django 4.0 on 2022-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_rename_tourdates_tourrequest_tour_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='days',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
