# Generated by Django 4.0 on 2022-03-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('categoryquery', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('content', models.TextField()),
                ('last_edit', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], default='publish', max_length=100)),
                ('img', models.ImageField(null=True, upload_to='blogs')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', to_field='categoryquery')),
            ],
        ),
    ]
