# Generated by Django 4.0 on 2021-12-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='activity_id',
            new_name='activity_name',
        ),
    ]
