# Generated by Django 4.0 on 2021-12-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('activity', '0004_packageprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packageprice',
            unique_together={('activity_name', 'package', 'name', 'host_id')},
        ),
    ]
