# Generated by Django 4.0 on 2021-12-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('activity', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=500)),
                ('lastname', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('mobile', models.CharField(default='', max_length=12)),
                ('address', models.CharField(default='', max_length=1000)),
                ('country', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default='', max_length=20)),
                ('paymenttype', models.CharField(default='', max_length=50)),
                ('Total', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.order'),
        ),
    ]
