# Generated by Django 4.0 on 2021-12-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_order_cart_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Total',
            new_name='total',
        ),
    ]
