# Generated by Django 4.0 on 2022-01-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_featureimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='what_to_expect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
