# Generated by Django 4.0 on 2022-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activity_latitude_activity_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featureimg'),
        ),
    ]
